language: node_js

services:
  - docker

node_js:
  - "6"

stages:
  - Linting and Building
  - test

cache:
  directories:
    - node_modules

env:
  global:
    - LAUNCHER=Node

jobs:
  include:
    - stage: Linting and Building
      before_install: skip
      env: STEP=LINT
      install: npm install eslint@4.7.x
      script: 'npm run lint && npm run lint_tests'
    - stage: Linting and Building
      before_install: skip
      env: STEP=BUILD
      install: npm install uglify-js@3.1.x
      script: 'npm run build'
    - stage: test
      before_install: skip
      install: npm install testem@1.18.4 qunit@2.4.1
      matrix:
        include:
          env:
            - LAUNCHER=Chrome
            - LAUNCHER=Firefox
    - stage: test
      node_js: "9"
      addons:
        apt:
          packages:
          - libgif-dev
          - libpng-dev
          - libpango1.0-dev
    - stage: test
      node_js: "8"
      addons:
        apt:
          packages:
          - libgif-dev
          - libpng-dev
          - libpango1.0-dev
    - stage: test
      node_js: "6"
      addons:
        apt:
          packages:
          - libgif-dev
          - libpng-dev
          - libpango1.0-dev
    - stage: test
      node_js: "4"
      addons:
        apt:
          packages:
          - libgif-dev
          - libpng-dev
          - libpango1.0-dev

script: 'npm run build:fast && testem ci --port 8080 -f testem.json -l $LAUNCHER'

# before_install:
#   - sudo apt-get install -qq libgif-dev libpng-dev libjpeg-dev libpango1.0-dev
  # libcairo2-dev is preinstalled

dist: trusty
